---
language: python
dist: xenial
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sox libsox-fmt-mp3
install:
  - python3 setup.py build
  - python3 setup.py install
  - python3 -m pip install .[dev]
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest -v --doctest-modules
